name: Build UI and Uplaod artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI repository
        uses: actions/checkout@v2

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build UI
        run: NODE_ENV=production npm run build:final

      - name: Upload compiled files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-ui
          path: build/static

      - name: Checkout to LabelStudio-Backend repository
        uses: actions/checkout@v2
        with:
          repository: manigandanp/label-studio
          path: label-studio
          token: ${{ secrets.LABEL_STUDIO_BACKEND_REPO_TOKEN }} # Create a Personal Access Token and add it to this repository 
          persist-credentials: false # Important for custom token

      - name: Move compiled files to Backend dist folder
        run: |
          ls -ll label-studio/label_studio/frontend/dist/lsf
          rm -rf label-studio/label_studio/frontend/dist/lsf/js
          rm -rf label-studio/label_studio/frontend/dist/lsf/css
          mv build/static/* label-studio/label_studio/frontend/dist/lsf

      - name: Push changes to Backend repository
        env:
          LABEL_STUDIO_BACKEND_REPO_TOKEN: ${{ secrets.LABEL_STUDIO_BACKEND_REPO_TOKEN }}
        run: |
          cd label-studio
          git config user.name "Manigandan P"
          git config user.email "sabarinathan305@gmail.com"
          git remote set-url origin https://x-access-token:$LABEL_STUDIO_BACKEND_REPO_TOKEN@github.com/manigandanp/label-studio.git
          git add label_studio/frontend/dist/lsf
          git commit -m "Update compiled UI files"
          git push
